server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-square-glitter-an9nqofl.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dS4qWVcxBf2U

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true